name: Continuous integration
on: push

jobs:
  ci:
    runs-on: maven:3.9-eclipse-temurin-11
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: unit tests
        run: mvn test
